---
development:
  url: <%= "postgresql://deploy:deploy@127.0.0.1/gadetrungvang?encoding=utf8&pool=5&timeout=5000".gsub('?', '_development?') %>

test:
  url: <%= "postgresql://deploy:deploy@127.0.0.1/gadetrungvang?encoding=utf8&pool=5&timeout=5000".gsub('?', '_test?') %>

production:
  url: <%= "postgresql://deploy:deploy@127.0.0.1/gadetrungvang?encoding=utf8&pool=5&timeout=5000".gsub('?', '_production?') %>
